import uuid
from django.conf import settings
from django.db import migrations, models
import django.core.validators, django.db.models.deletion
class Migration(migrations.Migration):
    initial=True; dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
      migrations.CreateModel(name="Position",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("symbol",models.CharField(max_length=20,unique=True)),("quantity",models.DecimalField(decimal_places=6,max_digits=18)),("average_price",models.DecimalField(decimal_places=6,max_digits=18,validators=[django.core.validators.MinValueValidator(0)])),("version",models.PositiveBigIntegerField(default=0)),("updated_at",models.DateTimeField(auto_now=True))]),
      migrations.CreateModel(name="ReconciliationRun",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("started_at",models.DateTimeField(auto_now_add=True)),("completed_at",models.DateTimeField(null=True)),("status",models.CharField(default="RUNNING",max_length=20)),("discrepancies",models.JSONField(default=list)),("correlation_id",models.CharField(db_index=True,max_length=64))]),
      migrations.CreateModel(name="RiskPolicy",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("active",models.BooleanField(default=True,unique=True)),("max_order_notional",models.DecimalField(decimal_places=2,default=10000,max_digits=18,validators=[django.core.validators.MinValueValidator(0)])),("max_position_notional",models.DecimalField(decimal_places=2,default=50000,max_digits=18,validators=[django.core.validators.MinValueValidator(0)])),("max_daily_exposure",models.DecimalField(decimal_places=2,default=100000,max_digits=18,validators=[django.core.validators.MinValueValidator(0)])),("max_symbol_exposure",models.DecimalField(decimal_places=2,default=25000,max_digits=18,validators=[django.core.validators.MinValueValidator(0)])),("stale_market_data_seconds",models.PositiveIntegerField(default=30))]),
      migrations.CreateModel(name="TradingControl",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("singleton",models.BooleanField(default=True,unique=True)),("trading_enabled",models.BooleanField(default=False)),("reason",models.CharField(default="Initial safe state",max_length=255)),("changed_at",models.DateTimeField(auto_now=True)),("changed_by",models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name="Order",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("idempotency_key",models.CharField(max_length=128,unique=True)),("symbol",models.CharField(db_index=True,max_length=20)),("side",models.CharField(choices=[("BUY","Buy"),("SELL","Sell")],max_length=4)),("quantity",models.DecimalField(decimal_places=6,max_digits=18,validators=[django.core.validators.MinValueValidator(1e-06)])),("filled_quantity",models.DecimalField(decimal_places=6,default=0,max_digits=18,validators=[django.core.validators.MinValueValidator(0)])),("limit_price",models.DecimalField(blank=True,decimal_places=6,max_digits=18,null=True)),("status",models.CharField(choices=[("PENDING_APPROVAL","Pending approval"),("ACCEPTED","Accepted"),("PARTIAL","Partial"),("FILLED","Filled"),("REJECTED","Rejected"),("CANCELLED","Cancelled")],db_index=True,default="PENDING_APPROVAL",max_length=24)),("broker_order_id",models.CharField(blank=True,max_length=128,null=True,unique=True)),("strategy",models.CharField(db_index=True,default="manual",max_length=100)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("created_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to=settings.AUTH_USER_MODEL))]),
      migrations.AddConstraint(model_name="order",constraint=models.CheckConstraint(condition=models.Q(("filled_quantity__lte",models.F("quantity"))),name="filled_lte_quantity")),
    ]
